export const assetsIndex = {
  images: {
    //Skybox: { name: 'Skybox', path: './assets/textures/skybox4.png' },
    Skybox: { name: 'Skybox', path: './assets/textures/skybox5-512.jpg', type: '4x3' },
  },
  textures: {
    UVGrid: { name: 'UVGrid', path: './assets/textures/UV_Grid_Sm.png' },
    Asphalt: { name: 'Asphalt', path: './assets/textures/asphalt.jpg' },
    Grass_Map: { name: 'Grass_Map', path: './assets/textures/grass_map_sq_512.jpg' },
    Grass_Normal: { name: 'Grass_Normal', path: './assets/textures/grass_normal.jpg' },
    LongGrass_Map: { name: 'LongGrass_Map', path: './assets/textures/longgrass_map.jpg' },
    Darkstone_Map: { name: 'Darkstone_Map', path: './assets/textures/darkstone_map.jpg' },
    Road_Map: { name: 'Road_Map', path: './assets/textures/roadhalf_map.png' },
    Road_Normal: { name: 'Road_Normal', path: './assets/textures/road_normal2.png' },
    Metalplate_Map: { name: 'Metalplate_Map', path: './assets/textures/metalplate_map.jpg' },
    Metalplate_Normal: { name: 'Metalplate_Normal', path: './assets/textures/metalplate_normal.jpg' },
    Wheel_Map: { name: 'Wheel_Map', path: './assets/textures/wheel_map.jpg' },
    Tree_Map: { name: 'Tree_Map', path: './assets/textures/tree_map.png' },
    GuardRails_Map: { name: 'GuardRails_Map', path: './assets/textures/guardrails_map.jpg' },
    GuardRails_Normal: { name: 'GuardRails_Normal', path: './assets/textures/guardrails_normal.jpg' },
    LightMap_Map: { name: 'LightMap_Map', path: './assets/textures/lightmap.jpg' },
    Forest_Map: { name: 'Forest_Map', path: './assets/textures/forest.png' },
    Concrete_Map: { name: 'Concrete_Map', path: './assets/textures/concrete_map.png' },
    Concrete_Normal: { name: 'Concrete_Normal', path: './assets/textures/concrete_normal.png' },
    Skyline_Map: { name: 'Skyline_Map', path: './assets/textures/skyline_map.png' },
    Perlin: { name: 'Perlin', path: './assets/textures/perlin_map.png' },
    TestQuadrants_Map: { name: 'TestQuadrants_Map', path: './assets/textures/testQuadrants_map.jpg' },
  },
  SkyBox: {
    One: { name: 'One', path: './assets/textures/skybox1.png', type: '4x3' },
    Two: { name: 'Five', path: './assets/textures/skybox5-512.png', type: '4x3' },
  },
};
