export const assetsIndex = {
  images: {
    Perlin: { name: 'Perlin', path: './assets/textures/perlin_map.png' },
    Skybox: { name: 'Skybox', path: './assets/textures/skybox5-256.png', type: '4x3' },
  },
  textures: {
    Asphalt: { name: 'Asphalt', path: './assets/textures/asphalt.jpg' },
    Billboards: { name: 'Billboards', path: './assets/textures/billboards_map.jpg' },
    Bumpy_Normal: { name: 'Bumpy_Normal', path: './assets/textures/bumpy-normal.jpg' },
    Concrete_Map: { name: 'Concrete_Map', path: './assets/textures/concrete_map.png' },
    Concrete_Normal: { name: 'Concrete_Normal', path: './assets/textures/concrete_normal.png' },
    Darkstone_Map: { name: 'Darkstone_Map', path: './assets/textures/darkstone_map.jpg' },
    Forest_Map: { name: 'Forest_Map', path: './assets/textures/forest.png' },
    Grass_Map: { name: 'Grass_Map', path: './assets/textures/grass_map_sq_512.jpg' },
    Grass_Normal: { name: 'Grass_Normal', path: './assets/textures/grass_normal.jpg' },
    Grass_Alpha: { name: 'Grass_Alpha', path: './assets/textures/grass_alpha.png' },
    GuardRails_Map: { name: 'GuardRails_Map', path: './assets/textures/guardrails_map.jpg' },
    Chainlink_Map: { name: 'Chainlink_Map', path: './assets/textures/chainlink_map.png' },
    GuardRails_Normal: { name: 'GuardRails_Normal', path: './assets/textures/guardrails_normal.jpg' },
    LightMap_Map: { name: 'LightMap_Map', path: './assets/textures/lightmap.jpg' },
    LocationIcon_Map: { name: 'LocationIcon_Map', path: './assets/textures/location_map.png' },
    LongGrass_Map: { name: 'LongGrass_Map', path: './assets/textures/longgrass_map.jpg' },
    Metalplate_Map: { name: 'Metalplate_Map', path: './assets/textures/metalplate_map.jpg' },
    Metalplate_Normal: { name: 'Metalplate_Normal', path: './assets/textures/metalplate_normal.jpg' },
    Perlin: { name: 'Perlin', path: './assets/textures/perlin_map.png' },
    Road_Map: { name: 'Road_Map', path: './assets/textures/roadhalf_map.png' },
    Road_Normal: { name: 'Road_Normal', path: './assets/textures/road_normal2.png' },
    RoadRacingLine_Map: { name: 'RoadRacingLine_Map', path: './assets/textures/racingLine_map.png' },
    Skyline_Map: { name: 'Skyline_Map', path: './assets/textures/skyline2_map.png' },
    TestQuadrants_Map: { name: 'TestQuadrants_Map', path: './assets/textures/testQuadrants_map.jpg' },
    Tree_Map: { name: 'Tree_Map', path: './assets/textures/tree_map.png' },
    UVGrid: { name: 'UVGrid', path: './assets/textures/UV_Grid_Sm.jpg' },
  },
};
