export const lightsIndex = [
  {
    name: 'ambientLight',
    type: 'AmbientLight',
    addToScene: true,
    //color: 0x000000,
    intensity: 0.1,
  },
  {
    name: 'directionalLight',
    type: 'DirectionalLight',
    addToScene: true,
    color: 0xfff0f0,
    intensity: 0.01,
    position: [0, 300, 250],
    castShadow: true,
    helperEnabled: true,
    target: [0, 0, 0],
    shadow: {
      bias: 0,
      mapWidth: 2048,
      mapHeight: 2048,
      camera: {
        near: 0,
        far: 400,
        top: 200,
        right: 200,
        bottom: -200,
        left: -200,
      },
    },
  },
  {
    name: 'pointLight',
    type: 'PointLight',
    addToScene: true,
    color: 0xffffff,
    intensity: 0.34,
    position: [0, 200, 0],
    visible: false,
  },
  {
    name: 'hemisphereLight',
    type: 'HemisphereLight',
    addToScene: true,
    color: 0xc8c8c8,
    intensity: 0.5,
    position: [0, 0, 0],
    visible: false,
  },
];
