import { GrassMaterial } from '../custom/geometries/grass';

export const materialsIndex = [
  {
    name: 'green',
    type: 'MeshLambertMaterial',
    color: 0x2f350c,
    side: 'FrontSide',
    wireframe: false,
  },
  {
    name: 'red',
    type: 'MeshLambertMaterial',
    //color: 0xff0000,
    color: 0xffffff,
    side: 'FrontSide',
    wireframe: false,
    blending: 'CustomBlending',
    blendEquation: 'AddEquation',
    blendSrc: 'OneMinusSrcColorFactor',
    opacity: 0.76,
    map: {
      name: 'Grassclump_Map',
      repeat: [1, 1],
      wrapping: 'RepeatWrapping',
      rotation: Math.PI,
    },
    alphaMap: {
      name: 'Grassclump_Alpha',
      wrapping: 'RepeatWrapping',
      repeat: [1, 1],
      rotation: Math.PI,

    },
    normalMap: {
      name: 'Grassclump_Normal',
      repeat: [1, 1],
      normalScale: [0.5, 0.5],
      wrapping: 'RepeatWrapping',
      //rotation: Math.PI * 0.25,
    },
    transparent: true,
    smartAlpha: true,
    smartAlphaThreshold: 0.6,
    shininess: 0,
    specular: 0x666666,
  },
  {
    name: 'mappedFlat',
    type: 'MeshPhongMaterial',
    color: 0xffffff,
    map: {
      name: 'UVGrid',
      repeat: [1, 1],
    },
    side: 'DoubleSide',
    wireframe: false,
    emissive: 0x000022,
    shininess: 100,
    //polygonOffset: true,
    ///polygonOffsetFactor: -1,
  },
  {
    name: 'wireFrame',
    type: 'MeshPhongMaterial',
    color: 0xff0000,
    side: 'FrontSide',
    wireframe: true,
    wireframeLinewidth: 5,
    emissive: 0x000000,
  },
  {
    name: 'road',
    type: 'MeshPhongMaterial',
    color: 0x666666,
    map: {
      name: 'Road_Map',
      wrapping: 'MirroredRepeatWrapping',
      repeat: [2, 1],
    },
    lightMap: {
      name: 'LightMap_Map',
      repeat: [5, 5],
      lightMapIntensity: 0.9,//0.1,
      wrapping: 'MirroredRepeatWrapping',
    },
    normalMap: {
      name: 'Road_Normal',
      wrapping: 'MirroredRepeatWrapping',
      normalScale: [0.2, 0.2],
    },
    shininess: 5,
    specular: 0x888877,
    side: 'FrontSide',
    wireframe: false,
    emissive: 0x000000,
    clipping: true,
  },
  {
    name: 'roadRacingLine',
    type: 'MeshPhongMaterial',
    color: 0x222222,
    map: {
      name: 'RoadRacingLine_Map',
      wrapping: 'MirroredRepeatWrapping',
      repeat: [2, 0.1],
    },
    shininess: 1,
    transparent: true,
    opacity: 0.2,
    specular: 0x444444,
    side: 'FrontSide',
    wireframe: false,
    clipping: true,
    smartAlpha: true,
    polygonOffset: 2,
    polygonOffsetFactor: 1,
   // blending: 'A\Blending',
  },
  {
    name: 'GrassMaterial',
    type: 'MeshPhongMaterial',
    //color: 0xdddddd,
    color: 0x62682c,
    side: 'FrontSide',
    //customMaterial: GrassMaterial,
    map: {
      name: 'Grass_Map',
      repeat: [1, 1],
      wrapping: 'MirroredRepeatWrapping',
    },
    normalMap: {
      name: 'Bumpy_Normal',
      repeat: [1.5, 1.5],
      normalScale: [0.06, 0.06],
      wrapping: 'RepeatWrapping',
      rotation: Math.PI * 0.25,
    },
    // alphaMap: {
    //   name: 'Perlin',
    //   wrapping: 'RepeatWrapping',

    // },
    // transparent: true,
    // normalMap: {
    //   name: 'UVGrid',//'Grass_Normal',
    //   normalScale: [10, 10],
    //   repeat: [1, 1]
    // },
    // normalMap: {
    //   name: 'GuardRails_Normal',
    //   wrapping: 'RepeatWrapping',
    //   repeat: [1, 1],
    //   rotation: Math.PI * 0.25,
    // },


    // lightMap: {
    //   name: 'LightMap_Map',
    //   repeat: [1, 1],
    //   lightMapIntensity: 0.1,
    // },
    wireframe: false,
    //emissive: 0x000000,
    shininess: 0,
    specular: 40,
  },
  {
    name: 'LongGrassMaterial',
    type: 'MeshLambertMaterial',
    color: 0x555555,
    //customMaterial: GrassMaterial,
    map: {
      name: 'LongGrass_Map',
      repeat: [1, 3],
      wrapping: 'MirroredRepeatWrapping',
      rotation: Math.PI * 0.5,
    },
    //flatShading: true,
    // normalMap: {
    //   name: 'Grass_Normal',
    //   normalScale: [1, 1],
    // },

    // lightMap: {
    //   name: 'LightMap_Map',
    //   repeat: [1, 1],
    //   lightMapIntensity: 0.1,
    // },
    side: 'FrontSide',
    wireframe: false,
    emissive: 0x000000,
    shininess: 0,
  },
  {
    name: 'GrassEdgeMaterial',
    type: 'MeshLambertMaterial',
    color: 0x555555,
    //blending: 'AdditiveBlending',
    opacity: 0.1,
    //customMaterial: GrassMaterial,
    map: {
      name: 'Grass_Map',
      repeat: [0.5, 1],
      wrapping: 'RepeatWrapping',
      rotation: Math.PI,
    },
    alphaMap: {
      name: 'Grass_Alpha',
      wrapping: 'RepeatWrapping',
      repeat: [1, 1],
    },
    transparent: true,
    side: 'FrontSide',
  },
  {
    name: 'kerb',
    type: 'MeshPhongMaterial',
    color: 0xaaaaaa,
    map: {
      name: 'Concrete_Map',
      wrapping: 'RepeatWrapping',
      repeat: [1, 1],
    },
    normalMap: {
      name: 'Concrete_Normal',
      wrapping: 'RepeatWrapping',
      repeat: [1, 1],
      normalScale: [1, 1],
    },
    shininess: 0,
    specular: 0x000000,
    side: 'FrontSide',
    wireframe: false,
    emissive: 0x000000,
    clipping: true,
    transparent: true,
  },
  {
    name: 'guardRails',
    type: 'MeshPhongMaterial',
    color: 0xaaaaaa,
    map: {
      name: 'GuardRails_Map',
      wrapping: 'RepeatWrapping',
      repeat: [1, 4],
    },
    normalMap: {
      name: 'GuardRails_Normal',
      wrapping: 'RepeatWrapping',
      repeat: [1, 4],
    },
    shininess: 100,
    specular: 0x888888,
    side: 'DoubleSide',
    wireframe: false,
    emissive: 0x000000,
    clipping: true,
    useVertexColors: true,
  },
  {
    name: 'chainlink',
    type: 'MeshPhongMaterial',
    color: 0xffffff,
    map: {
      name: 'Chainlink_Map',
      wrapping: 'RepeatWrapping',
      repeat: [5, 5],
    },
    shininess: 50,
    specular: 0xffffff,
    side: 'DoubleSide',
    wireframe: false,
    emissive: 0xaaaaaa,
    transparent: true,
    clipping: true,
  },
  {
    name: 'skyline',
    type: 'MeshPhongMaterial',
    color: 0xbbbbbb,
    map: {
      name: 'Skyline_Map',
      wrapping: 'RepeatWrapping',
      repeat: [5, 1],
    },
    shininess: 0,
    smartAlpha: true,
    smartAlphaThreshold: 0.9,
    specular: 0x000000,
    side: 'BackSide',
    wireframe: false,
    emissive: 0x000000,
    //transparent: true,
  },
  {
    name: 'LocationIcon',
    type: 'SpriteMaterial',
    color: 0xffffff,
    map: {
      name: 'LocationIcon_Map',
    },
  },
];
