export const materialsIndex = [
  {
    name: 'redMapped',
    type: 'MeshPhongMaterial',
    color: 0xff0000,
    map: 'UVGrid',
    side: 'DoubleSide',
    wireframe: false,
  },
  {
    name: 'mappedFlat',
    type: 'MeshPhongMaterial',
    color: 0xffffff,
    map: 'UVGrid',
    side: 'FrontSide',
    wireframe: false,
    emissive: 0x000022,
  },
  {
    name: 'wireFrame',
    type: 'MeshPhongMaterial',
    color: 0xff0000,
    map: 'UVGrid',
    side: 'FrontSide',
    wireframe: true,
    emissive: 0x000000,
  },
  {
    name: 'asphalt',
    type: 'MeshPhongMaterial',
    color: 0xffffff,
    map: 'Asphalt',
    side: 'FrontSide',
    wireframe: false,
    emissive: 0x000000,
  },
];
